version: '2'
services:
  service:
    build: .
    environment:
      - WS_URI=http://1.1.3.7:8545
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3

  mockup:
    build: 
      context: .
      dockerfile: Dockerfile-mockup
    ports:
      - "0.0.0.0:8002:80"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./mockup:/var/www:ro"
