apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file production.yml convert -c
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mockup
  name: mockup
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 80
  selector:
    io.kompose.service: mockup
status:
  loadBalancer: {}
