apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file production.yml convert -c
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mockup
  name: mockup
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mockup
    spec:
      containers:
      - image: registry.gitlab.com/lo-enterprise/blockchain-document-validateur/mockup
        name: mockup
        ports:
        - containerPort: 80
          hostIP: 0.0.0.0
        resources: {}
      restartPolicy: Always
status: {}
